name: Run Scheduled Workflow And Create Issue When Numba Is Compatible With New Python Version
on:
  workflow_dispatch:
  repository_dispatch:
    types: [check_python]
jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write 
    steps:
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/TDAmeritrade/stumpy/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Test",
            "body": "This issue was automatically created by the stumpy-bot. \n\n"
            }' \
          --fail
