name: Numba-Python Compatibility Check
on:
  workflow_dispatch:
  repository_dispatch:
    types: [check_numba_python_compatibility]
jobs:
  check_numba_python_compatibility:
    env:
      python-version: '3.12'
    runs-on: ubuntu-latest
    environment: API_Access
    permissions:
      issues: write 
    steps:
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
        continue-on-error: true
      - name: Display Python Version
        id: python
        run: |
          python -c "import sys; print(sys.version)"
          echo "version=$(python setup.py --version)" >> GITHUB_OUTPUT
        shell: bash
      - name: Compare Installed Python Version Versus Required
        if: startsWith(${{ steps.python.version }}, ${{ env.python-version }})
        run: echo "HERE"
        shell: bash
      #- name: Checkout STUMPY
      #  uses: actions/checkout@v3
      #  with:
      #    repository: TDAmeritrade/stumpy
      #- name: Install STUMPY And Other Dependencies
      #  run: python -m pip install --editable .[ci] 2> stderr.txt || true
      #  shell: bash
      #- name: Check installation
      #  run: |
      #    if [[ `grep RuntimeError stderr.txt | wc -l` -gt "0" ]]; then
      #      echo "Installation failed (gracefully)"
      #      cat stderr.txt
      #      exit 0
      #    else
      #      echo "Installation succeeded on Python ${{ env.python-version }}"
      #      exit 1
      #    fi
      #- name: Run STUMPY Unit Tests
      #  id: unittests
      #  if: failure()
      #  run: ./test.sh unit
      #  shell: bash
      #- name: Create New STUMPY Issue Using REST API
      #  if: ${{ failure() && steps.unittests.conclusion != 'failure' }}
      #  run: |
      #    curl --request POST \
      #    --url https://api.github.com/repos/TDAmeritrade/stumpy/issues \
      #    --header 'Authorization: token ${{ secrets.ACCESS_TOKEN }}' \
      #    --header 'Content-Type: application/json' \
      #    --data '{
      #      "title": "Numba Python Version ${{ env.python-version }} Compatibility Update",
      #      "body": "This issue was automatically created by the stumpy-bot.\n\n Numba is now compatible with Python version ${{ env.python-version }} (see https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
      #      }' \
      #    --fail
      #  shell: bash
