name: Run Scheduled Workflow And Create Issue When Numba Is Compatible With New Python Version
on:
  workflow_dispatch:
  repository_dispatch:
    types: [check_numba_python_compatibility]
jobs:
  check_numba_python_compatibility:
    runs-on: ubuntu-latest
    environment: API_Access
    permissions:
      issues: write 
    steps:
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/TDAmeritrade/stumpy/issues \
          --header 'Authorization: token ${{ secrets.ACCESS_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data '{
            "title": "Test: Please ignore",
            "body": "This issue was automatically created by the stumpy-bot.\n\n Numba is now compatible with Python version X.Y"
            }' \
          --fail
