name: Run Scheduled Workflow And Create Issue When Numba Is Compatible With New Python Version
on:
  workflow_dispatch:
  repository_dispatch:
    types: [check_numba_python_compatibility]
jobs:
  check_numba_python_compatibility:
    env:
      python-version: '3.11'
    runs-on: ubuntu-latest
    environment: API_Access
    permissions:
      issues: write 
    steps:
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"
        shell: bash
      - name: Checkout STUMPY
        uses: actions/checkout@v3
        with:
          repository: TDAmeritrade/stumpy
      - name: Install STUMPY And Other Dependencies
        run: python -m pip install --editable .[ci]
        shell: bash 
      # - name: Create New STUMPY Issue Using REST API
      #   run: |
      #     curl --request POST \
      #     --url https://api.github.com/repos/TDAmeritrade/stumpy/issues \
      #     --header 'Authorization: token ${{ secrets.ACCESS_TOKEN }}' \
      #     --header 'Content-Type: application/json' \
      #     --data '{
      #       "title": "Test: Please ignore",
      #       "body": "This issue was automatically created by the stumpy-bot.\n\n Numba is now compatible with Python version ${{ env.python-version }} (see https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
      #       }' \
      #     --fail
      #   shell: bash
