name: Check Ray
on:
  workflow_dispatch:
  repository_dispatch:
    types: [check_ray]
jobs:
  check_ray:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout STUMPY
        uses: actions/checkout@v4
        with:
          repository: TDAmeritrade/stumpy
      - name: Get Required Python Version
        id: python
        run: |
          python -m pip install requests packaging
          echo "version=$(python ./ray_python_version.py)" >> $GITHUB_OUTPUT
        shell: bash
      - uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ steps.python.outputs.version }}"
      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"
        shell: bash
      - name: Upgrade Pip
        run: python -m pip install --upgrade pip
        shell: bash
       - name: Checkout STUMPY Again
        uses: actions/checkout@v4
        with:
          repository: TDAmeritrade/stumpy
      - name: Install STUMPY And Other Dependencies
        run: python -m pip install --editable .[ci]
        shell: bash
      - name: Install Ray
        run: python -m pip install --upgrade ray
        shell: bash
      - name: Run Black
        run: black --check --diff ./
        shell: bash
      - name: Run Flake8
        run: flake8 ./
        shell: bash
      - name: Install OpenMP
        run: |
             if [ "$RUNNER_OS" == "macOS" ]; then
                  echo "Installing OpenMP"
                  brew install libomp
                  echo "Linking OpenMP"
                  brew link --force libomp
                  echo "Find OpenMP Linking Location"
                  libfile=`brew list libomp --verbose | grep libomp.dylib`
                  echo $libfile
                  echo "Changing  @rpath for the omppool.cpython-x-darwin.so shared object to look in $libfile"
                  ls "$(python -c 'import site; print(site.getsitepackages()[0])')"/numba/np/ufunc/omppool.*.so | xargs install_name_tool -change @rpath/libomp.dylib $libfile
             fi
        shell: bash
      - name: Show Full Numba Environment
        run: python -m numba -s
        shell: bash
      - name: Run Unit Tests
        run: ./test.sh unit
        shell: bash
